version: "3.7"

services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./frontend/db_data:/bitnami/mariadb
  wordpress:
    image: bitnami/wordpress-nginx:latest
    environment:
      - WORDPRESS_DATABASE_HOST=db
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=admin123
      - WORDPRESS_EMAIL=me@quanna.dev
      - API_ENDPOINT=http://host.docker.internal:8080
    ports:
      - "8084:8080"
    volumes:
      - ./frontend/wordpress_data:/bitnami/wordpress
    depends_on:
      - db

volumes:
  db_data:
    driver: local